src/main/java/com/sparta/chairingproject/config/JwtUtil.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberResponseDto.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java
=> feat : 내 정보 조회 기능 추가

src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/request/MemberPasswordRequest.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberResponse.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java
=> feat : 비밀번호 변경 기능 추가

src/main/java/com/sparta/chairingproject/domain/menu/repository/MenuRepository.java, src/main/java/com/sparta/chairingproject/domain/order/controller/OrderController.java, src/main/java/com/sparta/chairingproject/domain/order/dto/request/OrderRequest.java, src/main/java/com/sparta/chairingproject/domain/order/dto/response/OrderResponse.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/order/entity/OrderStatus.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java
- 주문하기 기능 추가
- 주문하기 기능 구동 확인을 위한 테스트코드 추가(생성자는 지움)
- Order 엔티티 내부 정적 팩토리 메서드로 캡슐화
- 주문상태를 Enum 클래스로 수정
- 메뉴 선택은 2개 이상 가능하도록 다대다 관계로 설정(중간테이블에 중첩되는 중간테이블 방지)
어떤 변경 사항이 있나요?
=> feat: 주문하기 기능 추가

src/main/java/com/sparta/chairingproject/config/security/WebSecurityConfig.java, src/main/java/com/sparta/chairingproject/domain/coupon/controller/CouponController.java, src/main/java/com/sparta/chairingproject/domain/coupon/dto/CouponRequest.java, src/main/java/com/sparta/chairingproject/domain/coupon/dto/CouponResponse.java, src/main/java/com/sparta/chairingproject/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/chairingproject/domain/coupon/repository/CouponRepository.java, src/main/java/com/sparta/chairingproject/domain/coupon/service/CouponService.java
어드민(Admin) 권한을 가진 사용자만 쿠폰을 생성할 수 있도록 @Secured를 활용하여 권한 검증을 구현.
쿠폰 이름, 수량, 할인 가격을 입력받아 새로운 쿠폰을 생성.
어떤 변경 사항이 있나요?
=> #3 feat: 쿠폰 생성 기능 추가

src/main/java/com/sparta/chairingproject/config/security/WebSecurityConfig.java, src/main/java/com/sparta/chairingproject/domain/Issuance/entity/Issuance.java, src/main/java/com/sparta/chairingproject/domain/Issuance/repository/IssuanceRepository.java, src/main/java/com/sparta/chairingproject/domain/coupon/controller/CouponController.java, src/main/java/com/sparta/chairingproject/domain/coupon/dto/CouponRequest.java, src/main/java/com/sparta/chairingproject/domain/coupon/dto/CouponResponse.java, src/main/java/com/sparta/chairingproject/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/chairingproject/domain/coupon/repository/CouponRepository.java, src/main/java/com/sparta/chairingproject/domain/coupon/service/CouponService.java, src/test/java/com/sparta/chairingproject/coupon/CreateCouponTest.java
쿠폰 발급 기능을 추가.
이 기능은 사용자(User) 권한을 가진 회원만 쿠폰을 발급받을 수 있도록 설계.
발급된 쿠폰은 발급 기록(Issuance)으로 저장.
발급 과정에서 중복 발급 방지, 수량 관리.
어떤 변경 사항이 있나요?
=> Feature/9 쿠폰 발급 기능 추가

src/main/java/com/sparta/chairingproject/config/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/chairingproject/config/exception/customException/GlobalExceptions.java, src/main/java/com/sparta/chairingproject/config/exception/customException/HasNotPermissionException.java, src/main/java/com/sparta/chairingproject/config/exception/customException/NotValidCookieException.java, src/main/java/com/sparta/chairingproject/config/exception/customException/NotValidTokenException.java, src/main/java/com/sparta/chairingproject/config/exception/dto/NotValidRequestParameter.java, src/main/java/com/sparta/chairingproject/config/exception/dto/ResponseExceptionCode.java, src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java
- Add GlobalExceptionHandler
- Can manage every exception in Enum Class
- Use GlobalExceptions Keyword instead of your exception code.
어떤 변경 사항이 있나요?
=> feat: 글로벌 예외처리 추가

src/main/java/com/sparta/chairingproject/config/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/chairingproject/config/exception/customException/GlobalException.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java
- 예외처리 로직에서 빨간줄 생긴부분 제대로 구조 맞춰서 수정해뒀습니다. 죄송합니다 이것을 반영해주세요
어떤 변경 사항이 있나요?
=> fix: GlobalExceptionHandler 구조 수정 및 오류 해결

src/main/java/com/sparta/chairingproject/domain/common/dto/MemberIdDto.java
=> feat: memberIdDto 추가

src/main/java/com/sparta/chairingproject/domain/common/dto/RequestDto.java
=> refactor: RequestDto 가져오기 추가

src/main/java/com/sparta/chairingproject/domain/store/controller/StoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java, src/test/java/com/sparta/chairingproject/domain/store/service/StoreServiceTest.java
Store에서 가게 등록 요청에 관한 로직 추가.  
-> responsebody 제거
유효성 검증 추가
테스트 코드 추가 
어떤 변경 사항이 있나요?
=> Feature/2 가게 등록 요청

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/order/controller/OrderController.java, src/main/java/com/sparta/chairingproject/domain/order/dto/request/OrderCancelRequest.java, src/main/java/com/sparta/chairingproject/domain/order/dto/response/OrderCancelResponse.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/order/entity/OrderStatus.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/test/java/com/sparta/chairingproject/mockitoTest/OrderServiceMockitoTest.java
- 유저만 요청하는 유저 전용 주문 취소 API 추가
- 주문은 실제로 취소 요청이라는 상태로 변경됨
- 추후에 요청된 취소 요청 상태를 취소 상태로 전환하는 사장님 전용 메서드 추가 예정
어떤 변경 사항이 있나요?
=> feat: 주문 취소하기 기능 추가

src/main/java/com/sparta/chairingproject/ChairingProjectApplication.java, src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/common/dto/RequestDto.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/request/MemberPasswordRequest.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberOrderResponse.java, src/main/java/com/sparta/chairingproject/domain/member/repository/MemberRepository.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java
=> feat : 내 주문 내역 조회 기능

src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberReservationResponse.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/reservation/repository/ReservationRepository.java
=> 내 예약 내역 조회 기능

src/main/java/com/sparta/chairingproject/domain/Issuance/repository/IssuanceRepository.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberCouponResponse.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberIssuanceResponse.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/main/java/com/sparta/chairingproject/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/chairingproject/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/chairingproject/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreRepository.java
=> 내 쿠폰 조회 기능

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/request/CreateReservationRequest.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/request/UpdateReservationRequest.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/response/ReservationResponse.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/ReservationStatus.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationService.java
- Reservation entity에 ReservationStatus 필드를 추가하였습니다.
- 예약 상태 변경 기능을 만들었습니다.
- 관련 ExceptionCode 추가하였습니다.
어떤 변경 사항이 있나요?
=> feat: 예약 상태 변경 기능 추가

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/Issuance/repository/IssuanceRepository.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/response/MemberIssuanceResponse.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/order/controller/OrderController.java, src/main/java/com/sparta/chairingproject/domain/order/dto/request/OrderStatusChangeRequest.java, src/main/java/com/sparta/chairingproject/domain/order/dto/request/OrderStatusUpdateRequest.java, src/main/java/com/sparta/chairingproject/domain/order/dto/response/OrderStatusChangeResponse.java, src/main/java/com/sparta/chairingproject/domain/order/dto/response/OrderStatusUpdateResponse.java, src/main/java/com/sparta/chairingproject/domain/order/entity/OrderStatus.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/main/java/com/sparta/chairingproject/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/request/CreateReservationRequest.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/request/UpdateReservationRequest.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/response/ReservationResponse.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/ReservationStatus.java, src/main/java/com/sparta/chairingproject/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/chairingproject/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreRepository.java
- 다양한 검증로직 추가(아래)
- 취소 요청 을 하는 상태변경은 하지 못함(유저의 요청이어야 함)
- 완료 또는 취소 상태의 주문의 상태는 변경 못함
- 테이블이 모두 차 있을때는 진행중 상태로 변경 불가
- 대기중 상태에서는 입장 으로만 변경 가능
- 입장에서는 진행중 또는 취소로만 변경가능(대기인이 들어가거나 들어오지않고 그냥 다른가게 간 경우)
어떤 변경 사항이 있나요?
=> feat: 사장님이 주문 상태 변경하는 로직 추가

src/main/java/com/sparta/chairingproject/domain/order/dto/response/OrderPageResponse.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/main/java/com/sparta/chairingproject/domain/store/controller/StoreController.java
- 가게에 들어온 주문을 조회하는 로직 추가
- 기본적으로 전체조회(startDate, endDate 미입력시)
- 시작일, 종료일 입력시 days 라는 기간 변수를 토대로 2일 기준으로 조회
- 주문 이력은 생성일 기준 내림차순조회
- API 위치는 "사장님"이 "가게" 에서 사용한다는 조건으로 store 에 작성
- Response 객체는 Response 내부에서 팩토리 메서드로 매핑되어 반환
어떤 변경 사항이 있나요?
=> feat: 사장님이 가게의 주문 조회기능 추가

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/menu/controller/MenuController.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/request/MenuRequest.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/menu/repository/MenuRepository.java, src/main/java/com/sparta/chairingproject/domain/menu/service/MenuService.java
- 사장님 권한이 있어야만 실행가능
- 사장님 권한이 있어도, 자기 가게의 메뉴만 생성 가능
- 같은 이름의 메뉴는 생성 불가능
- 엔티티 팩토리 메서드로 캡슐화
=> feat: 메뉴 생성 로직 추가

src/main/java/com/sparta/chairingproject/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/chairingproject/domain/member/dto/request/MemberPasswordRequest.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java
(여기에 변경사항 기입) 
멤버 서비스 테스트코드 추가
=> feat : 멤버 서비스 테스트 코드

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/menu/controller/MenuController.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/request/MenuUpdateRequest.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuUpdateResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/menu/repository/MenuRepository.java, src/main/java/com/sparta/chairingproject/domain/menu/service/MenuService.java
- soldOut 필드 추가하여 매진상태 수정 가능
- 필요한 필드 값만 수정할 수 있게 Request 에서 Null 로 받을 수 있게 설정
어떤 변경 사항이 있나요?
=> feat: 메뉴 수정기능 추가

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/review/controller/ReviewController.java, src/main/java/com/sparta/chairingproject/domain/review/dto/ReviewRequest.java, src/main/java/com/sparta/chairingproject/domain/review/entity/Review.java, src/main/java/com/sparta/chairingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/test/java/com/sparta/chairingproject/domain/review/controller/ReviewControllerTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
- 가게에 대한 리뷰를 작성할 수 있는 기능 구현
- 가게 상태가 PENDING인 경우 리뷰 작성 불가 처리
- 주문 상태가 완료가 아닌 경우 리뷰 작성 불가 처리
- 리뷰 작성 테스트 코드:
리뷰 작성 성공 시 리뷰가 정상적으로 저장되는지 테스트
가게 상태가 PENDING인 경우 리뷰 작성이 실패하는지 테스트
주문 상태가 완료가 아닌 경우 리뷰 작성이 실패하는지 테스트
존재하지 않는 가게에 대해 리뷰를 작성할 경우 예외 처리 확인
=> 리뷰 작성 기능 && 테스트 코드

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/menu/controller/MenuController.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/request/MenuUpdateRequest.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuDeleteResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuUpdateResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/menu/repository/MenuRepository.java, src/main/java/com/sparta/chairingproject/domain/menu/service/MenuService.java, src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/review/controller/ReviewController.java, src/main/java/com/sparta/chairingproject/domain/review/dto/ReviewRequest.java, src/main/java/com/sparta/chairingproject/domain/review/entity/Review.java, src/main/java/com/sparta/chairingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/test/java/com/sparta/chairingproject/domain/review/controller/ReviewControllerTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
- inActive 필드를 추가하여 메뉴 삭제를 논리적 삭제로 처리
- 이미 삭제된 메뉴는 삭제 처리하지 않게 예외처리
어떤 변경 사항이 있나요?
=> feat: 메뉴 삭제기능 추가

src/main/java/com/sparta/chairingproject/ChairingProjectApplication.java, src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/config/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/chairingproject/config/security/WebSecurityConfig.java, src/main/java/com/sparta/chairingproject/domain/common/scheduler/MemberCleanupScheduler.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/repository/MemberRepository.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java
회원 탈퇴 기능 및 Scheduler 활용
어떤 변경 사항이 있나요?
=> feat : 회원 탈퇴 기능 및 Scheduler 활용

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/store/controller/StoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreAdminResponse.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreOwnerResponse.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/mapper/StoreMapper.java, src/main/java/com/sparta/chairingproject/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java
- 사장이 내 가게를 조회하는 거임 
- 사용자 id 와 가게 id 로 가게 조회
어떤 변경 사항이 있나요?
=> feat: 가게 조회 (사장)

src/main/java/com/sparta/chairingproject/domain/comment/dto/CommentRequest.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java
- 댓글 작성 서비스의 모든 주요 로직을 검증하는 테스트 코드 추가.
- 예외 처리 및 성공 시나리오를 명확히 검증하여 기능의 안정성을 보장.
어떤 변경 사항이 있나요?
=> 댓글 작성 테스트 코드 추가

src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/order/controller/OrderController.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java
시나리오
1. 메뉴가 선택되고, 웨이팅을 신청할 때, 테이블에 자리가 있으면 ADMISSION 상태로 주문 생성된다.
2. 메뉴를 선택하지 않고, 웨이팅을 신청할 때, 테이블에 자리가 없으면 WAITING 상태로 주문이 생성된다.
3. 메뉴를 선택하지 않고, 웨이팅을 신청할 때, 테이블에 자리가 없고, WAITING 인 상태가 3팀인 경우 3이 반환이 된다.
4. 선택된 메뉴 수와, 실제 메뉴 수가 일치하지 않으면 예외가 발생한다.
5. 주문 금액이 총 금액과 일치하지 않으면 예외가 발생한다.
어떤 변경 사항이 있나요?
=> test: createOrder 메서드 관련 테스트 코드

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/store/controller/AdminStoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/CloseStoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/entity/StoreRequestStatus.java, src/main/java/com/sparta/chairingproject/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/chairingproject/domain/store/service/AdminStoreService.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java
가게 주인의 가게 삭제 요청에 대한  관리자의 가게 삭제 승인 로직 (소프트 딜리트)
오류 수정 : 가게 승인 시 db상 approved 가 false -> true 바뀌지 않던 문제 발견 -> 해결 
postman에서 요청이 안되는 문제 발견 -> transactional 환경을 구축해서 해결  
어떤 변경 사항이 있나요?
=> 가게 삭제 요청에 관한 소프트 딜리트

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java
회원 탈퇴 테스트 코드 작성
어떤 변경 사항이 있나요?
=> feat : 회원 탈퇴 테스트 코드 작성

src/main/java/com/sparta/chairingproject/domain/store/controller/StoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/UpdateStoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java
- 가게 수정 기능 추가
- 가게 수정 요구를 하는 DTO 추가
- Store 클래스에 update 함수 추가
어떤 변경 사항이 있나요?
=> feat: 가게 수정 기능 추가

src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/order/service/OrderService.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java
시나리오
1. 존재하지 않는 주문 ID 로 요청 시 예외가 발생한다.
2. 요청자가 주문자가 아닌 경우 예외가 발생한다.
3. 해당 가게의 주문이 아닌 경우에 예외가 발생한다.
4. 주문 상태가 CANCELLED 인 경우에 예외가 발생한다.
5. 주문 상태가 COMPLETED 인 경우에 예외가 발생한다.
6. 정상적으로 주문 취소 요청이 처리된다.
어떤 변경 사항이 있나요?
=> test: 주문 취소 요청하기 테스트 코드

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/response/ReservationListResponse.java, src/main/java/com/sparta/chairingproject/domain/reservation/dto/response/ReservationResponse.java, src/main/java/com/sparta/chairingproject/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationService.java
- 예약 다건 조회 기능 추가
- 반환 시 페이지 정보와 예약 목록을 같이 반환함
- 기존 코드에 네이버 코드 컨벤션 적용
어떤 변경 사항이 있나요?
=> Feat: 예약 다건 조회 기능 추가

src/main/java/com/sparta/chairingproject/domain/order/repository/OrderRepository.java, src/main/java/com/sparta/chairingproject/domain/review/controller/ReviewController.java, src/main/java/com/sparta/chairingproject/domain/review/entity/Review.java, src/main/java/com/sparta/chairingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
- 리뷰 작성 기능 수정
주문 한 건당 리뷰를 하나만 작성할 수 있도록 제한.
URL 경로에 orderId를 추가하여 리뷰 작성 시 주문 식별 가능.
이미 해당 주문에 리뷰가 존재하는 경우 예외 처리 추가.
- 테스트 코드 수정 및 추가
주문 한 건당 리뷰 하나 작성 제한에 대한 테스트 코드 추가.
반복되는 Given 부분을 @BeforeEach로 추출하여 테스트 코드 리팩토링.
어떤 변경 사항이 있나요?
=> 리뷰 작성 기능 수정 && 테스트 코드 수정 및 추가

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/comment/repository/CommentRepository.java, src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java
- 리뷰 하나당 사장님 댓글을 하나만 작성할 수 있도록 로직을 추가.
- 이미 댓글이 존재하는 경우, COMMENT_ALREADY_EXISTS 예외 처리.
- 댓글 제한 로직에 대한 테스트 코드 추가: 댓글 작성 실패 - 이미 댓글 존재.
- 반복되는 Given 부분을 @BeforeEach로 분리하여 중복 제거.
어떤 변경 사항이 있나요?
=> 댓글 작성 제한 로직 추가 및 테스트 코드 추가, 리팩토링

src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java
시나리오
1. 가게가 없을때 예외가 발생한다
2. 기간 입력 없이 호출할 경우 전체 주문 목록을 반환한다
3. startDate 없이 endDate 만 입력하면 days 기준으로 앞 기간을 계산하여 조회한다.
4. endDate 없이 startDate 만 입력하면 days 기준으로 뒤 기간을 계산하여 조회한다.
5. startDate 와 endDate 가 모두 입력되면 지정된 기간에 해당하는 주문 목록을 반환한다.
어떤 변경 사항이 있나요?
=> test: 사장님 주문 조회기능 테스트코드

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/comment/repository/CommentRepository.java, src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/main/java/com/sparta/chairingproject/domain/review/controller/ReviewController.java, src/main/java/com/sparta/chairingproject/domain/review/dto/ReviewWithCommentResponse.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
- **리뷰당 댓글 하나로 제한된 로직에 따라 조회 로직 수정**
- 기존: 다수의 리뷰와 각 리뷰에 달린 다수의 댓글을 그룹화하여 처리.
- 변경: 각 리뷰에 대해 댓글 하나를 직접 조회하여 연결하는 방식으로 단순화.
1. **서비스 로직 변경**
- `ReviewWithCommentResponse`로 매핑 처리.
- 댓글이 없을 경우 null로 반환.
- 기존 Map 로직 제거.
2. **테스트 코드 리팩토링 및 추가**
- 댓글이 있는 경우, 없는 경우에 대한 테스트 추가.
- 가게가 존재하지 않을 때 예외 처리 테스트 추가.
어떤 변경 사항이 있나요?
=> 리뷰 조회 기능 수정

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/review/controller/ReviewController.java, src/main/java/com/sparta/chairingproject/domain/review/entity/Review.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java
- 사용자가 본인이 작성한 리뷰를 수정할 수 있는 기능을 추가
- 리뷰의 내용(content)과 평점(rating)을 업데이트
- 해당 리뷰가 존재하지 않거나 리뷰를 작성한 사용자가 아닐경우 예외처리
- 테스트 코드는 머지된 후에 작성할 예정
어떤 변경 사항이 있나요?
=> 리뷰 수정 기능 추가

src/main/java/com/sparta/chairingproject/domain/menu/dto/request/MenuRequest.java, src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java
시나리오
1. 정상적으로 메뉴를 생성한다
2. 가게를 찾을 수 없을 경우 예외가 발생: NOT_FOUND_MENU
3. 요청한 사용자가 가게의 주인이 아닌 경우 예외가 발생: ONLY_OWNER_ALLOWED
4. 중복된 메뉴 이름으로 요청할 경우 예외 발생: DUPLICATED_MENU
어떤 변경 사항이 있나요?
=> test: 사장님 메뉴 생성 로직 테스트 코드

src/main/java/com/sparta/chairingproject/domain/store/dto/StoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/dto/UpdateStoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java, src/test/java/com/sparta/chairingproject/domain/store/service/StoreServiceTest.java
- 가게 등록 신청 성공 테스트
- 가게 등록 실패 테스트 : 이미 등록된 가게 수가 최대 
- 승인된 가게 목록 조회 성공 테스트
- 조회 가능한 가게가 없을 경우 실패 테스트
- 가게 정보 수정 성공 테스트
- 가게 정보 수정 실패 테스트 : 사용자 정보 없음
- 가게 정보 수정 실패 테스트 : 가게 정보 없음
어떤 변경 사항이 있나요?
=> TEST : 가게 스토어 서비스 테스트

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/comment/controller/CommentController.java, src/main/java/com/sparta/chairingproject/domain/comment/entity/Comment.java, src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java
- 사용자가 작성한 댓글을 수정할 수 있는 기능 구현
- 댓글의 content 필드 업데이트
- 존재하지 않는 댓글 요청 시: NOT_FOUND_COMMENT 예외 발생
- 댓글이 해당 리뷰에 연결되지 않은 경우: NOT_MATCHING_COMMENT_AND_REVIEW 예외 발생
- 댓글 작성 권한이 없는 사용자가 요청 시: NOT_AUTHOR_OF_COMMENT 예외 발생
어떤 변경 사항이 있나요?
=> 댓글 수정 기능 추가

src/main/java/com/sparta/chairingproject/domain/menu/dto/request/MenuRequest.java, src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java
시나리오
1. 정상적으로 메뉴가 수정된다
2. 가게를 찾을 수 없을 경우 예외 발생: NOT_FOUND_STORE
3. 요청한 사용자가 가게의 주인이 아닌 경우 예외 발생: ONLY_OWNER_ALLOWED
4. 메뉴를 찾을 수 없을 경우 예외 발생: NOT_FOUND_MENU
5. 메뉴 정보가 부분적으로 업데이트 되는 경우: 일부만 제공 헀을 때, 그 부분만 업데이트 된다.
어떤 변경 사항이 있나요?
=> test: 사장님 메뉴 수정 로직 테스트코드

src/main/java/com/sparta/chairingproject/domain/store/dto/UpdateStoreStatusRequest.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/store/service/AdminStoreServiceTest.java
- 모든 가게 조회 성공 테스트
- 단일 가게 조회 성공 테스트
- 단일 가게 조회 실패 테스트 : 잘못된 ID
- 가게 상태 변경 성공 테스트 : 승인
- 가게 상태 변경 성공 테스트 : 거절
- 가게 상태 변경 실패 테스트 : 잘못된 상태 값
- 가게 삭제 성공 테스트
- 가게 삭제 실패 테스트 - 잘못된 ID
- 가게 삭제 실패 테스트 - 이미 삭제된 가게
=> TEST : 관리자 스토어 서비스 테스트

src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java
시나리오
- 정상적으로 메뉴 삭제
- 가게를 찾을 수 없는 경우 예외 발생: NOT_FOUND_STORE
- 사용자가 가게 주인이 아닌 경우 예외 발생: ONLY_OWNER_ALLOWED
- 메뉴를 찾을 수 없는 경우 예외 발생: NOT_FOUND_MENU
어떤 변경 사항이 있나요?
=> test: 사장님 메뉴 삭제 로직 테스트 추가

src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java
=> refactor : 회원 탈퇴 기능 수정

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/comment/controller/CommentController.java, src/main/java/com/sparta/chairingproject/domain/comment/entity/Comment.java, src/main/java/com/sparta/chairingproject/domain/comment/repository/CommentRepository.java, src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
- 댓글을 삭제(소프트 딜리)하여 deletedAt에 삭제 시간을 기록.
- 리뷰 조회 로직 수정 : 리뷰에 연결된 댓글 조회 시 삭제된 댓글은 제외.
어떤 변경 사항이 있나요?
=> 댓글 삭제 기능 추가

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/main/java/com/sparta/chairingproject/domain/review/controller/ReviewController.java, src/main/java/com/sparta/chairingproject/domain/review/entity/Review.java, src/main/java/com/sparta/chairingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/main/java/com/sparta/chairingproject/domain/store/dto/UpdateStoreStatusRequest.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java, src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java, src/test/java/com/sparta/chairingproject/domain/store/service/AdminStoreServiceTest.java
시나리오
- 정상적으로 메뉴 목록을 반환한다
- 가게를 찾을수 없을 경우 예외가 발생: NOT_FOUND_STORE
- 요청한 사용자가 가게 주인이 아닌 경우 예외가 발생한다: ONLY_OWNER_ALLOWED
- 가게에 메뉴가 없는 경우 빈 목록을 반환한다
어떤 변경 사항이 있나요?
=> test: 사장님 메뉴 조회 로직 테스트 코드

src/main/java/com/sparta/chairingproject/domain/reservation/dto/request/CreateReservationRequest.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/chairingproject/util/AuthUtils.java, src/test/java/com/sparta/chairingproject/domain/reservation/ReservationServiceTest.java, src/test/java/com/sparta/chairingproject/util/AuthUtilsTest.java
- ReservationService에 있던 유저 확인 부분을 AuthUtiils로 분리함
- 예약 생성 및 AuthUtils 테스트 코드 작성
어떤 변경 사항이 있나요?
=> Test: 예약 생성 및 AuthUtils 테스트 코드 작성

src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
테스트 시나리오
- 리뷰 수정 성공
- 작성자가 아닌 경우 수정 실패
- 이미 삭제된 리뷰 수정 실패
- 리뷰 삭제 성공
- 작성자가 아닌 경우 삭제 실패에 대한 테스트
- 이미 삭제된 리뷰 삭제 실패
어떤 변경 사항이 있나요?
=> 리뷰 수정 및 삭제 기능에 대한 테스트 코드 추가

src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java
테스트 시나리오
- 댓글 수정 성공 테스트 코드 작성
- 댓글 수정 실패 테스트 코드 추가 (존재하지 않는 댓글, 권한 없는 OWNER, 이미 삭제된 댓글, 댓글이 리뷰와 연결되지 않음)
- 댓글 삭제 성공 테스트 코드 작성
- 댓글 삭제 실패 테스트 코드 추가 (존재하지 않는 댓글, 권한 없는 OWNER, 이미 삭제된 댓글)
어떤 변경 사항이 있나요?
=> 댓글 수정 및 삭제 기능에 대한 테스트 코드 추가

src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java, src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java
- 테스트코드를 위해 만들었던 생성자는 모두 제거하고 기존의 생성자를 사용하는 로직으로 변경
- ReflectionTestUtils 을 이용하여 Id 값 설정
- OrderTest 전체 리팩토링 및 테스트 통과 확인
어떤 변경 사항이 있나요?
=> refactor: 테스트 코드에 사용한 생성자 제거 및 기본 생성자 사용

src/main/java/com/sparta/chairingproject/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java
=> 멤버 테스트코드 수정

src/main/java/com/sparta/chairingproject/domain/reservation/entity/ReservationStatus.java, src/test/java/com/sparta/chairingproject/domain/reservation/ReservationServiceTest.java, src/test/java/com/sparta/chairingproject/util/AuthUtilsTest.java
- ReservationStatus의 validateTransition 함수에서 현재 status가 아닌 targetStatus를 기준으로 판단하도록 수정
- ReservationStatus의 validateTransition 함수에 거절, 취소 시 에러 코드 추가
- AuthUtils의 member 생성자 사용 부분 수정
- 예약 취소 테스트 코드 작성
어떤 변경 사항이 있나요?
=> Test: 예약 취소 테스트 코드 작성

src/main/java/com/sparta/chairingproject/domain/store/dto/StoreResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java, src/test/java/com/sparta/chairingproject/domain/store/service/StoreServiceTest.java
- 가게 등록 신청 성공 테스트
- 가게 등록 실패 테스트 : 이미 등록된 가게가 최대 개수일 경우
- 가게 등록 실패 테스트 : 잘못된 영업시간 입력
- 가게 조회 실패 테스트 : 가게 운영 중지
- 승인된 가게 목록 조회 성공 테스트
- 가게 상세 조회 성공 테스트
- 조회 가능한 가게가 없을 경우 실패 테스트
- 가게 정보 수정 성공 테스트
- 가게 정보 수정 실패 테스트 : 사용자 정보 없음
- 가게 정보 수정 실패 테스트 : 가게 정보 없음
- 가게 상세 정보 조회 실패 테스트 : 가게 정보 없음
- 가게 삭제 요청 성공 테스트
- 가게 삭제 요청 실패 테스트 : 이미 삭제 요청됨
- 가게 소유자 가게 조회 성공 테스트
- 가게 소유자 가게 조회 실패 테스트 : 가게 없음
- 가게 소유자 가게 조회 실패 테스트 : 승인 대기 상태
어떤 변경 사항이 있나요?
=> TEST: 생성자를 제거 하고 reflectionTest 로 대체 후 실행

src/main/java/com/sparta/chairingproject/domain/store/dto/StoreAdminResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/service/AdminStoreService.java, src/test/java/com/sparta/chairingproject/domain/store/service/AdminStoreServiceTest.java
- adminStoreServiceTest 코드 추가
어떤 변경 사항이 있나요?
=> Test: admin store service Test 코드 추가 

src/test/java/com/sparta/chairingproject/domain/reservation/ReservationServiceTest.java
- 예약 다건 조회 테스트 코드 작성
어떤 변경 사항이 있나요?
=> Test: 예약 다건 조회 테스트 코드 작성

src/main/java/com/sparta/chairingproject/domain/Issuance/entity/Issuance.java, src/main/java/com/sparta/chairingproject/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/Reservation.java, src/test/java/com/sparta/chairingproject/domain/member/controller/MemberControllerTest.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java
=> 멤버 종합 테스트 코드 작성

src/main/java/com/sparta/chairingproject/domain/Issuance/entity/Issuance.java, src/main/java/com/sparta/chairingproject/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/order/dto/request/OrderRequest.java, src/main/java/com/sparta/chairingproject/domain/order/dto/response/OrderResponse.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreAdminResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/service/AdminStoreService.java, src/test/java/com/sparta/chairingproject/domain/member/controller/MemberControllerTest.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java, src/test/java/com/sparta/chairingproject/domain/order/controller/OrderControllerTest.java, src/test/java/com/sparta/chairingproject/domain/reservation/ReservationServiceTest.java, src/test/java/com/sparta/chairingproject/domain/store/service/AdminStoreServiceTest.java, src/test/resources/application-test.properties
테스트용 aplication-test.properties 를 추가해뒀습니다. H2 를 사용하는 방식입니다.(아마도)
통합 테스트 시나리오 목록
- 정상 주문 생성: 여유 테이블 있을 때
- 정상 주문 생성: 메뉴 없이 요청
- 존재하지 않는 가게로 주문 요청
- 잘못된 메뉴 포함된 주문 요청
- 결제 금액 불일치
- 여유 테이블이 없는 경우는 WAITING 상태로 생성
어떤 변경 사항이 있나요?
=> test: 주문 생성 로직 통합테스트 작성

src/main/java/com/sparta/chairingproject/config/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/chairingproject/domain/coupon/controller/CouponController.java, src/test/java/com/sparta/chairingproject/domain/coupon/controller/CouponControllerTest.java
- MethodArgumentNotValidException을 처리하기 위한 글로벌 익셉션 핸들러 추가.
요청 객체의 필드 순서에 따라 검증 오류 메시지를 정렬하여 반환.
테스트 시나리오
- 쿠폰 생성 성공
- 쿠폰 생성 실패 - 중복된 이름
- 쿠폰 조회 성공
- 쿠폰 발급 성공
- 쿠폰 발급 실패 - 쿠폰 없음
- 쿠폰 발급 실패 - 이미 발급받은 쿠폰
- 쿠폰 발급 실패 - 재고 부족
- 쿠폰 생성 실패 - validation 예외
어떤 변경 사항이 있나요?
=> 쿠폰 통합 테스트 추가, validation 글로벌 익셉션 추가

src/test/java/com/sparta/chairingproject/domain/order/controller/OrderControllerTest.java
테스트 시나리오
- 주문 취소 요청 로직 성공: CANCEL_REQUEST
- 주문 취소 요청 로직 실패 주문자 불일치: ONLY_ORDER_ALLOWED
- 주문 취소 요청 로직 실패 가게 불일치: NOT_ORDER_THIS_STORE
- 주문 취소 요청 로직 실패 주문 상태 오류: CANCELLED_COMPLETED_NOT_ALLOWED
- 주문 취소 요청 로직 실패 주문 ID 없을때: NOT_FOUND_ORDER
어떤 변경 사항이 있나요?
=> test: 주문 취소 요청 로직 통합테스트

src/main/java/com/sparta/chairingproject/config/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/chairingproject/domain/coupon/controller/CouponController.java, src/test/java/com/sparta/chairingproject/domain/coupon/controller/CouponControllerTest.java, src/test/java/com/sparta/chairingproject/domain/order/controller/OrderControllerTest.java
테스트 시나리오
- 테이블에 여유가 있을 경우 orderStatus 는 ADMISSION
- 테이블에 여유가 없는 경우 orderStatus 는 WAITING
- 잘못된 storeId 로 요청할 경우 404 NOT_FOUND_STORE
어떤 변경 사항이 있나요?
=> test: 자리 선점 기능 통합테스트

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/test/java/com/sparta/chairingproject/domain/review/controller/ReviewControllerTest.java
- 리뷰 생성 성공
- 리뷰 생성 실패 - 이미 작성된 리뷰
- 리뷰 생성 실패 - 삭제된 가게
- 리뷰 생성 실패 - 팬딩 상태의 가게
- 리뷰 생성 실패 - 찾을 수 없는 주문
- 리뷰 생성 실패 - 완료되지 않은 주문
- 리뷰 생성 실패 - validation 예외
어떤 변경 사항이 있나요?
=> 리뷰 작성 통합 테스트

src/main/java/com/sparta/chairingproject/domain/order/dto/request/OrderStatusUpdateRequest.java, src/main/java/com/sparta/chairingproject/domain/order/entity/Order.java, src/test/java/com/sparta/chairingproject/domain/order/controller/OrderControllerTest.java
테스트 시나리오
- 주문 상태 변경 성공 : 주문 상태를 WAITING -> ADMISSION 으로 변경한다.
- 주문 상태 변경 실패 : 존재하지 않는 가게 NOT_FOUND_STORE
- 주문 상태 변경 실패 : 존재하지 않는 주문 NOT_FOUND_ORDER
- 주문 상태 변경 실패 : 가게 주인이 아닌 사용자가 요청 ONLY_OWNER_ALLOWED
어떤 변경 사항이 있나요?
=> test: 주문 상태 변경 통합 테스트작성

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/config/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/chairingproject/domain/comment/entity/Comment.java, src/main/java/com/sparta/chairingproject/domain/comment/service/CommentService.java, src/main/java/com/sparta/chairingproject/domain/common/entity/Timestamped.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/repository/MemberRepository.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/review/entity/Review.java, src/main/java/com/sparta/chairingproject/domain/review/service/ReviewService.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java, src/test/java/com/sparta/chairingproject/domain/member/controller/MemberControllerTest.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java, src/test/java/com/sparta/chairingproject/domain/store/controller/StoreControllerTest.java
- **TimeStamped에 deletedAt 필드 추가**
- 엔티티 삭제 함수 이름을 delete()로 통일
- 삭제된 상태는 DELETED로 변경
- TimeStamped를 상속 받는 엔티티에 있는 deletedAt 필드 삭제
- 삭제 관련 boolean 필드 삭제
- 삭제된 필드 관련 로직을 오류가 나지 않게 수정함
- import 최적화 및 필요 없는 코드 삭제
어떤 변경 사항이 있나요?
=> Refactor: TimeStamped에 deletedAt 필드 추가

src/test/java/com/sparta/chairingproject/domain/comment/controller/CommentControllerTest.java, src/test/java/com/sparta/chairingproject/domain/review/controller/ReviewControllerTest.java
추가된 테스트 시나리오
- 리뷰 조회 성공
- 리뷰 수정 성공
- 리뷰 삭제 성공
- 댓글 작성 성공
- 댓글 수정 성공
- 댓글 삭제 성공
컨트롤러 커버리지 100%
어떤 변경 사항이 있나요?
=> 리뷰 , 댓글 컨트롤러 테스트 완료

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/menu/controller/MenuController.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/request/MenuUpdateRequest.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuDeleteResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuDetailResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuUpdateResponse.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/MenuStatus.java, src/main/java/com/sparta/chairingproject/domain/menu/repository/MenuRepository.java, src/main/java/com/sparta/chairingproject/domain/menu/service/MenuService.java, src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java
- 삭제관련 로직을 Enum 클래스로 사장님이 상태를 변경할 수 있도록 수정
- 관리자 권한으로 DELETED 상태인 메뉴를 삭제를 위해 deletedAt 에 값을 넣는 로직 작성
어떤 변경 사항이 있나요?
=> 삭제관련 로직 상태 관리 방식으로 변경

src/main/java/com/sparta/chairingproject/ChairingProjectApplication.java, src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java, src/main/java/com/sparta/chairingproject/domain/menu/dto/response/MenuSummaryResponse.java, src/main/java/com/sparta/chairingproject/domain/review/dto/ReviewResponse.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreDetailsResponse.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java, src/main/resources/application.properties
캐싱 추가 및 캐싱이 레디스에 잘 key 값으로 들어가는지에 관하여 
어떤 변경 사항이 있나요?
=> 가게 상세 조회 캐싱 추가 

build.gradle, src/main/java/com/sparta/chairingproject/config/JwtUtil.java, src/main/java/com/sparta/chairingproject/config/S3Config.java, src/main/java/com/sparta/chairingproject/config/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/chairingproject/domain/auth/controller/AuthController.java, src/main/java/com/sparta/chairingproject/domain/auth/service/AuthService.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/request/CheckPasswordRequest.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/resources/application.properties, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java
=> 멤버 프로필 사진 업로드 기능 추가

src/main/java/com/sparta/chairingproject/domain/store/controller/StoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreOpenCloseRequest.java, src/main/java/com/sparta/chairingproject/domain/store/dto/StoreOpenCloseResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java
- 사장님이 가게 상태를 OPEN 하거나, BREAKTIME 을 걸거나, CLOSE 를 하는 등의 상태를 변경할 수 있는 로직 추가
어떤 변경 사항이 있나요?
=> feat: 사장님 가게 오픈 마감 임의 설정 기능

build.gradle, src/main/java/com/sparta/chairingproject/domain/order/service/OrderNotificationService.java, src/main/java/com/sparta/chairingproject/domain/order/service/RedisSubscriberService.java
- 기존의 Redis 채널 구독 및 메세지 발행 + WebSocket 메세지 송신 하던 부분을 Redis 와 WebSocket 부분으로 분리
- 분리해서 각각의 메세지 관련 로직의 확장성 확보
- WebSocket 메세지 전송하는 과정에서 Pub/Sub 구조의 메세지 여러개가 전달되는 문제 개선
어떤 변경 사항이 있나요?
=> 메세지 책임 분리 및 메세지 중복 전송 방지

.gitignore, build.gradle, src/main/java/com/sparta/chairingproject/config/security/WebSecurityConfig.java, src/main/java/com/sparta/chairingproject/domain/fcm/controller/FcmController.java, src/main/java/com/sparta/chairingproject/domain/fcm/dto/request/FcmMessageRequest.java, src/main/java/com/sparta/chairingproject/domain/fcm/dto/request/FcmRequest.java, src/main/java/com/sparta/chairingproject/domain/fcm/dto/response/FcmMessageResponse.java, src/main/java/com/sparta/chairingproject/domain/fcm/sevice/FcmService.java, src/main/java/com/sparta/chairingproject/domain/fcm/sevice/FcmServiceImpl.java
- fcm을 사용을 위한 코드를 작성하였습니다.
- 작동이 정상적으로 되는지 테스트만 한 상태입니다.
어떤 변경 사항이 있나요?
=> Feat: fcm 테스트 구현 완료

build.gradle, src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/config/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/chairingproject/config/security/WebSecurityConfig.java, src/main/java/com/sparta/chairingproject/domain/auth/dto/request/SigninRequest.java, src/main/java/com/sparta/chairingproject/domain/fcm/sevice/FcmServiceImpl.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/ReservationStatus.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationService.java
- 로그인 시 fcm 토큰을 사용자 정보와 함께 보냄
- 로그인 성공 시 redis에 <userId, zset<fcmToken>> 형태로 fcm 토큰을 저장함
- 유저가 여러 기기를 사용해도 모든 기기가 푸시 알림을 받을 수 있도록 구현함
- 예약하기, 예약 취소, 예약 상태 변경 시 관련된 유저에게 푸시 알림을 보내는 코드 추가
- fcm 토큰 및 메시지와 관련된 예외 코드 추가
- 예약 상태 변경 시 부족한 비즈니스 로직 추가
어떤 변경 사항이 있나요?
=> Feat: 레디스를 사용하여 FCM 토큰 관리 및 예약 상황에서 푸시 알림 전송

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/config/redis/RedisInitializer.java, src/main/java/com/sparta/chairingproject/domain/common/scheduler/PopularStoreBatch.java, src/main/java/com/sparta/chairingproject/domain/store/controller/PopularStoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/PopularStoreResponse.java, src/main/java/com/sparta/chairingproject/domain/store/entity/Store.java, src/main/java/com/sparta/chairingproject/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/chairingproject/domain/store/service/PopularStoreService.java
- 인기 가게 데이터를 주기적으로 갱신하는 배치 스케줄러 추가 (1시간 간격)
- 인기 가게 조회 API 추가 (/api/popular-stores)
- Redis를 활용한 캐시 관리 구현
- 주문 수 기준 상위 200개 가게를 필터링 후 리뷰 및 주문 데이터를 계산하여 상위 25개 가게 캐싱
- 초기 애플리케이션 실행 시 캐시 초기화 로직 추가
- Store 엔티티 내 리뷰 평균 점수 계산 메서드 추가
- StoreRepository에 주문 수 기준 상위 가게 조회 쿼리 작성
- 데이터가 없는 경우 예외 처리 (NOT_FOUND_DATA)
어떤 변경 사항이 있나요?
=> feat 인기 가게 캐싱 조회 기능 구현

.github/workflows/ci-redis.yml, .github/workflows/run-test.yml, compose.yaml, src/main/resources/application.properties, src/test/java/com/sparta/chairingproject/ChairingProjectApplicationTests.java, src/test/java/com/sparta/chairingproject/domain/comment/controller/CommentControllerTest.java, src/test/java/com/sparta/chairingproject/domain/coupon/controller/CouponControllerTest.java, src/test/java/com/sparta/chairingproject/domain/member/controller/MemberControllerTest.java, src/test/java/com/sparta/chairingproject/domain/order/controller/OrderControllerTest.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java, src/test/java/com/sparta/chairingproject/domain/reservation/ReservationIntegrationTest.java, src/test/java/com/sparta/chairingproject/domain/reservation/ReservationServiceTest.java, src/test/java/com/sparta/chairingproject/domain/review/controller/ReviewControllerTest.java, src/test/java/com/sparta/chairingproject/domain/store/controller/StoreControllerTest.java, src/test/java/com/sparta/chairingproject/mockitoTest/OrderServiceMockitoTest.java, src/test/resources/application-test.properties
- Dockerfile 생성
- run-test 라는 CI github 액션파일 생성
=> CI 를 깃허브 액션에서 동작하도록 설정 및 도커관련 기본적인 설정

docker-compose.yml
-docker-compose 에 version 필드 제거(더이상 필요없음)
=> fix: Redis 연결안되던거 수정5

docker-compose.yml
=> fix: Redis 연결안되던거 수정6

docker-compose.yml
- 레디스 서버가 완벽히 실행되고 나서 App 이 실행될 수 있도록 compose 설정 변경
=> fix: Redis 연결안되던거 수정9

src/main/resources/application.properties
=> fix: Redis 연결안되던거 수정10

build.gradle, src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java
- .env 파일을 읽어올 수 있도록 dotenv 의존성 추가 및 redisconfig 수정
=> fix: Redis 연결안되던거 수정11

src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java
- .env 파일을 읽어올 수 있도록 dotenv 의존성 추가 및 redisconfig 수정
=> fix: Redis 연결안되던거 수정12

src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java
=> fix: Redis 연결안되던거 수정13

docker-compose.yml
=> fix: Redis 연결안되던거 수정14

src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java
=> fix: Redis 연결안되던거 수정15

src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java
=> fix: Redis 연결안되던거 수정16

src/main/java/com/sparta/chairingproject/config/redis/RedisConfig.java, src/main/resources/application.properties
=> fix: Redis 연결안되던거 수정17

docker-compose.yml
=> feat: 그라파나 기본적으로 적용하기

build.gradle, src/main/java/com/sparta/chairingproject/config/JwtUtil.java, src/main/java/com/sparta/chairingproject/config/S3Config.java, src/main/java/com/sparta/chairingproject/config/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/chairingproject/config/security/WebSecurityConfig.java, src/main/java/com/sparta/chairingproject/domain/auth/controller/AuthController.java, src/main/java/com/sparta/chairingproject/domain/auth/service/AuthService.java, src/main/java/com/sparta/chairingproject/domain/common/service/S3Uploader.java, src/main/java/com/sparta/chairingproject/domain/member/controller/MemberController.java, src/main/java/com/sparta/chairingproject/domain/member/dto/request/CheckPasswordRequest.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/member/service/MemberService.java, src/main/java/com/sparta/chairingproject/domain/menu/controller/MenuController.java, src/main/java/com/sparta/chairingproject/domain/menu/entity/Menu.java, src/main/java/com/sparta/chairingproject/domain/menu/service/MenuService.java, src/main/java/com/sparta/chairingproject/domain/store/controller/StoreController.java, src/main/java/com/sparta/chairingproject/domain/store/dto/UpdateStoreRequest.java, src/main/java/com/sparta/chairingproject/domain/store/service/StoreService.java, src/main/resources/application.properties, src/test/java/com/sparta/chairingproject/ChairingProjectApplicationTests.java, src/test/java/com/sparta/chairingproject/domain/comment/service/CommentServiceTest.java, src/test/java/com/sparta/chairingproject/domain/coupon/service/CouponServiceTest.java, src/test/java/com/sparta/chairingproject/domain/member/service/MemberServiceTest.java, src/test/java/com/sparta/chairingproject/domain/menu/service/MenuServiceTest.java, src/test/java/com/sparta/chairingproject/domain/order/service/OrderServiceTest.java, src/test/java/com/sparta/chairingproject/domain/review/service/ReviewServiceTest.java, src/test/java/com/sparta/chairingproject/domain/store/service/AdminStoreServiceTest.java, src/test/java/com/sparta/chairingproject/domain/store/service/StoreServiceTest.java, src/test/java/com/sparta/chairingproject/util/AuthUtilsTest.java
=> 이미지 업로드 리팩토링

src/main/java/com/sparta/chairingproject/config/exception/enums/ExceptionCode.java, src/main/java/com/sparta/chairingproject/domain/common/entity/OutboxEvent.java, src/main/java/com/sparta/chairingproject/domain/member/entity/Member.java, src/main/java/com/sparta/chairingproject/domain/outbox/OutboxPublisher.java, src/main/java/com/sparta/chairingproject/domain/outbox/OutboxRepository.java, src/main/java/com/sparta/chairingproject/domain/outbox/OutboxScheduler.java, src/main/java/com/sparta/chairingproject/domain/outbox/entity/Outbox.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/chairingproject/domain/reservation/entity/ReservationEvent.java, src/main/java/com/sparta/chairingproject/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationNotificationService.java, src/main/java/com/sparta/chairingproject/domain/reservation/service/ReservationService.java
예약 관련 알림 기능을 트랜잭셔널 아웃박스 패턴 중 폴링 퍼블리셔 방식으로 변경하였습니다.
어떤 변경 사항이 있나요?
=> Feat: 예약 관련 알림 기능을 트랜잭셔널 아웃박스 패턴으로 변경

src/main/resources/application.properties
Reverts Team6Without6SH/Chairing-project#253
=> Revert "변경"
